version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: <user>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: <db>
    ports:
      - "5432:5432"

networks:
  default:
    external:
      name: my_network
